package io.github.shogowada.statictags

trait StaticTags {

  class Elements {
    lazy val a = ElementSpec("a", isSupposedToBeEmpty = false)
    lazy val abbr = ElementSpec("abbr", isSupposedToBeEmpty = false)
    lazy val address = ElementSpec("address", isSupposedToBeEmpty = false)
    lazy val area = ElementSpec("area", isSupposedToBeEmpty = true)
    lazy val article = ElementSpec("article", isSupposedToBeEmpty = false)
    lazy val aside = ElementSpec("aside", isSupposedToBeEmpty = false)
    lazy val audio = ElementSpec("audio", isSupposedToBeEmpty = false)
    lazy val b = ElementSpec("b", isSupposedToBeEmpty = false)
    lazy val base = ElementSpec("base", isSupposedToBeEmpty = true)
    lazy val bdi = ElementSpec("bdi", isSupposedToBeEmpty = false)
    lazy val bdo = ElementSpec("bdo", isSupposedToBeEmpty = false)
    lazy val blockquote = ElementSpec("blockquote", isSupposedToBeEmpty = false)
    lazy val body = ElementSpec("body", isSupposedToBeEmpty = false)
    lazy val br = ElementSpec("br", isSupposedToBeEmpty = true)
    lazy val button = ElementSpec("button", isSupposedToBeEmpty = false)
    lazy val canvas = ElementSpec("canvas", isSupposedToBeEmpty = false)
    lazy val caption = ElementSpec("caption", isSupposedToBeEmpty = false)
    lazy val cite = ElementSpec("cite", isSupposedToBeEmpty = false)
    lazy val code = ElementSpec("code", isSupposedToBeEmpty = false)
    lazy val col = ElementSpec("col", isSupposedToBeEmpty = true)
    lazy val colgroup = ElementSpec("colgroup", isSupposedToBeEmpty = false)
    lazy val data = ElementSpec("data", isSupposedToBeEmpty = false)
    lazy val datalist = ElementSpec("datalist", isSupposedToBeEmpty = false)
    lazy val dd = ElementSpec("dd", isSupposedToBeEmpty = false)
    lazy val del = ElementSpec("del", isSupposedToBeEmpty = false)
    lazy val dfn = ElementSpec("dfn", isSupposedToBeEmpty = false)
    lazy val div = ElementSpec("div", isSupposedToBeEmpty = false)
    lazy val dl = ElementSpec("dl", isSupposedToBeEmpty = false)
    lazy val dt = ElementSpec("dt", isSupposedToBeEmpty = false)
    lazy val em = ElementSpec("em", isSupposedToBeEmpty = false)
    lazy val embed = ElementSpec("embed", isSupposedToBeEmpty = true)
    lazy val fieldset = ElementSpec("fieldset", isSupposedToBeEmpty = false)
    lazy val figcaption = ElementSpec("figcaption", isSupposedToBeEmpty = false)
    lazy val figure = ElementSpec("figure", isSupposedToBeEmpty = false)
    lazy val footer = ElementSpec("footer", isSupposedToBeEmpty = false)
    lazy val form = ElementSpec("form", isSupposedToBeEmpty = false)
    lazy val h1 = ElementSpec("h1", isSupposedToBeEmpty = false)
    lazy val h2 = ElementSpec("h2", isSupposedToBeEmpty = false)
    lazy val h3 = ElementSpec("h3", isSupposedToBeEmpty = false)
    lazy val h4 = ElementSpec("h4", isSupposedToBeEmpty = false)
    lazy val h5 = ElementSpec("h5", isSupposedToBeEmpty = false)
    lazy val h6 = ElementSpec("h6", isSupposedToBeEmpty = false)
    lazy val head = ElementSpec("head", isSupposedToBeEmpty = false)
    lazy val header = ElementSpec("header", isSupposedToBeEmpty = false)
    lazy val hr = ElementSpec("hr", isSupposedToBeEmpty = true)
    lazy val html = ElementSpec("html", isSupposedToBeEmpty = false)
    lazy val i = ElementSpec("i", isSupposedToBeEmpty = false)
    lazy val iframe = ElementSpec("iframe", isSupposedToBeEmpty = false)
    lazy val img = ElementSpec("img", isSupposedToBeEmpty = true)
    lazy val input = ElementSpec("input", isSupposedToBeEmpty = true)
    lazy val ins = ElementSpec("ins", isSupposedToBeEmpty = false)
    lazy val kbd = ElementSpec("kbd", isSupposedToBeEmpty = false)
    lazy val keygen = ElementSpec("keygen", isSupposedToBeEmpty = true)
    lazy val label = ElementSpec("label", isSupposedToBeEmpty = false)
    lazy val legend = ElementSpec("legend", isSupposedToBeEmpty = false)
    lazy val li = ElementSpec("li", isSupposedToBeEmpty = false)
    lazy val link = ElementSpec("link", isSupposedToBeEmpty = true)
    lazy val main = ElementSpec("main", isSupposedToBeEmpty = false)
    lazy val map = ElementSpec("map", isSupposedToBeEmpty = false)
    lazy val mark = ElementSpec("mark", isSupposedToBeEmpty = false)
    lazy val meta = ElementSpec("meta", isSupposedToBeEmpty = true)
    lazy val meter = ElementSpec("meter", isSupposedToBeEmpty = false)
    lazy val nav = ElementSpec("nav", isSupposedToBeEmpty = false)
    lazy val noscript = ElementSpec("noscript", isSupposedToBeEmpty = false)
    lazy val `object` = ElementSpec("object", isSupposedToBeEmpty = false)
    lazy val ol = ElementSpec("ol", isSupposedToBeEmpty = false)
    lazy val optgroup = ElementSpec("optgroup", isSupposedToBeEmpty = false)
    lazy val option = ElementSpec("option", isSupposedToBeEmpty = false)
    lazy val output = ElementSpec("output", isSupposedToBeEmpty = false)
    lazy val p = ElementSpec("p", isSupposedToBeEmpty = false)
    lazy val param = ElementSpec("param", isSupposedToBeEmpty = true)
    lazy val pre = ElementSpec("pre", isSupposedToBeEmpty = false)
    lazy val progress = ElementSpec("progress", isSupposedToBeEmpty = false)
    lazy val q = ElementSpec("q", isSupposedToBeEmpty = false)
    lazy val rb = ElementSpec("rb", isSupposedToBeEmpty = false)
    lazy val rp = ElementSpec("rp", isSupposedToBeEmpty = false)
    lazy val rt = ElementSpec("rt", isSupposedToBeEmpty = false)
    lazy val rtc = ElementSpec("rtc", isSupposedToBeEmpty = false)
    lazy val ruby = ElementSpec("ruby", isSupposedToBeEmpty = false)
    lazy val s = ElementSpec("s", isSupposedToBeEmpty = false)
    lazy val samp = ElementSpec("samp", isSupposedToBeEmpty = false)
    lazy val script = ElementSpec("script", isSupposedToBeEmpty = false)
    lazy val section = ElementSpec("section", isSupposedToBeEmpty = false)
    lazy val select = ElementSpec("select", isSupposedToBeEmpty = false)
    lazy val small = ElementSpec("small", isSupposedToBeEmpty = false)
    lazy val source = ElementSpec("source", isSupposedToBeEmpty = true)
    lazy val span = ElementSpec("span", isSupposedToBeEmpty = false)
    lazy val strong = ElementSpec("strong", isSupposedToBeEmpty = false)
    lazy val style = ElementSpec("style", isSupposedToBeEmpty = false)
    lazy val sub = ElementSpec("sub", isSupposedToBeEmpty = false)
    lazy val sup = ElementSpec("sup", isSupposedToBeEmpty = false)
    lazy val table = ElementSpec("table", isSupposedToBeEmpty = false)
    lazy val tbody = ElementSpec("tbody", isSupposedToBeEmpty = false)
    lazy val td = ElementSpec("td", isSupposedToBeEmpty = false)
    lazy val template = ElementSpec("template", isSupposedToBeEmpty = false)
    lazy val textarea = ElementSpec("textarea", isSupposedToBeEmpty = false)
    lazy val tfoot = ElementSpec("tfoot", isSupposedToBeEmpty = false)
    lazy val th = ElementSpec("th", isSupposedToBeEmpty = false)
    lazy val thead = ElementSpec("thead", isSupposedToBeEmpty = false)
    lazy val time = ElementSpec("time", isSupposedToBeEmpty = false)
    lazy val title = ElementSpec("title", isSupposedToBeEmpty = false)
    lazy val tr = ElementSpec("tr", isSupposedToBeEmpty = false)
    lazy val track = ElementSpec("track", isSupposedToBeEmpty = true)
    lazy val u = ElementSpec("u", isSupposedToBeEmpty = false)
    lazy val ul = ElementSpec("ul", isSupposedToBeEmpty = false)
    lazy val `var` = ElementSpec("var", isSupposedToBeEmpty = false)
    lazy val video = ElementSpec("video", isSupposedToBeEmpty = false)
    lazy val wbr = ElementSpec("wbr", isSupposedToBeEmpty = true)

    def apply(name: String) = ElementSpec(name)
  }

  class Attributes {
    lazy val abbr = StringAttributeSpec("abbr")
    lazy val accept = CommaSeparatedStringAttributeSpec("accept")
    lazy val `accept-charset` = OrderedSetOfUniqueSpaceSeparatedStringAttributeSpec("accept-charset")
    lazy val accesskey = OrderedSetOfUniqueSpaceSeparatedStringAttributeSpec("accesskey")
    lazy val action = StringAttributeSpec("action")
    lazy val allowfullscreen = BooleanAttributeSpec("allowfullscreen")
    lazy val allowTransparency = TrueOrFalseAttributeSpec("allowTransparency")
    lazy val alt = StringAttributeSpec("alt")
    lazy val async = BooleanAttributeSpec("async")
    lazy val autocomplete = AutoCompleteAttributeSpec("autocomplete")
    lazy val autofocus = BooleanAttributeSpec("autofocus")
    lazy val autoplay = BooleanAttributeSpec("autoplay")
    lazy val border = StringAttributeSpec("border")
    lazy val challenge = StringAttributeSpec("challenge")
    lazy val capture = BooleanAttributeSpec("capture")
    lazy val charset = StringAttributeSpec("charset")
    lazy val checked = BooleanAttributeSpec("checked")
    lazy val cite = StringAttributeSpec("cite")
    lazy val `class` = SpaceSeparatedStringAttributeSpec("class")
    lazy val cols = IntegerAttributeSpec("cols")
    lazy val colspan = IntegerAttributeSpec("colspan")
    lazy val content = StringAttributeSpec("content")
    lazy val contenteditable = TrueOrFalseAttributeSpec("contenteditable")
    lazy val contextmenu = StringAttributeSpec("contextmenu")
    lazy val controls = BooleanAttributeSpec("controls")
    lazy val coords = CommaSeparatedIntegerAttributeSpec("coords")
    lazy val crossorigin = StringAttributeSpec("crossorigin")
    lazy val data = StringAttributeSpec("data")
    lazy val datetime = StringAttributeSpec("datetime")
    lazy val default = BooleanAttributeSpec("default")
    lazy val defer = BooleanAttributeSpec("defer")
    lazy val dir = StringAttributeSpec("dir")
    lazy val dirname = StringAttributeSpec("dirname")
    lazy val disabled = BooleanAttributeSpec("disabled")
    lazy val download = StringAttributeSpec("download")
    lazy val draggable = TrueOrFalseAttributeSpec("draggable")
    lazy val enctype = StringAttributeSpec("enctype")
    lazy val `for` = ForAttributeSpec("for")
    lazy val form = StringAttributeSpec("form")
    lazy val formaction = StringAttributeSpec("formaction")
    lazy val formenctype = StringAttributeSpec("formenctype")
    lazy val formmethod = StringAttributeSpec("formmethod")
    lazy val formnovalidate = BooleanAttributeSpec("formnovalidate")
    lazy val formtarget = StringAttributeSpec("formtarget")
    lazy val headers = SetOfUniqueSpaceSeparatedStringAttributeSpec("headers")
    lazy val height = IntegerAttributeSpec("height")
    lazy val hidden = BooleanAttributeSpec("hidden")
    lazy val high = BigDecimalAttributeSpec("high")
    lazy val href = StringAttributeSpec("href")
    lazy val hreflang = StringAttributeSpec("hreflang")
    lazy val `http-equiv` = StringAttributeSpec("http-equiv")
    lazy val icon = StringAttributeSpec("icon")
    lazy val id = StringAttributeSpec("id")
    lazy val inputmode = InputModeAttributeSpec("inputmode")
    lazy val integrity = StringAttributeSpec("integrity")
    lazy val is = StringAttributeSpec("is")
    lazy val ismap = BooleanAttributeSpec("ismap")
    lazy val keytype = StringAttributeSpec("keytype")
    lazy val kind = StringAttributeSpec("kind")
    lazy val label = StringAttributeSpec("label")
    lazy val lang = StringAttributeSpec("lang")
    lazy val list = StringAttributeSpec("list")
    lazy val loop = BooleanAttributeSpec("loop")
    lazy val low = BigDecimalAttributeSpec("low")
    lazy val manifest = StringAttributeSpec("manifest")
    lazy val max = BigDecimalAttributeSpec("max")
    lazy val maxlength = IntegerAttributeSpec("maxlength")
    lazy val media = StringAttributeSpec("media")
    lazy val mediagroup = StringAttributeSpec("mediagroup")
    lazy val method = StringAttributeSpec("method")
    lazy val min = BigDecimalAttributeSpec("min")
    lazy val minlength = IntegerAttributeSpec("minlength")
    lazy val multiple = BooleanAttributeSpec("multiple")
    lazy val muted = BooleanAttributeSpec("muted")
    lazy val name = StringAttributeSpec("name")
    lazy val nonce = StringAttributeSpec("nonce")
    lazy val novalidate = BooleanAttributeSpec("novalidate")
    lazy val open = BooleanAttributeSpec("open")
    lazy val optimum = BigDecimalAttributeSpec("optimum")
    lazy val pattern = RegexAttributeSpec("pattern")
    lazy val placeholder = StringAttributeSpec("placeholder")
    lazy val poster = StringAttributeSpec("poster")
    lazy val preload = StringAttributeSpec("preload")
    lazy val radiogroup = StringAttributeSpec("radiogroup")
    lazy val readonly = BooleanAttributeSpec("readonly")
    lazy val rel = SpaceSeparatedStringAttributeSpec("rel")
    lazy val required = BooleanAttributeSpec("required")
    lazy val reversed = BooleanAttributeSpec("reversed")
    lazy val role = StringAttributeSpec("role")
    lazy val rows = IntegerAttributeSpec("rows")
    lazy val rowspan = IntegerAttributeSpec("rowspan")
    lazy val sandbox = SetOfUniqueSpaceSeparatedStringAttributeSpec("sandbox")
    lazy val scope = StringAttributeSpec("scope")
    lazy val scoped = BooleanAttributeSpec("scoped")
    lazy val seamless = BooleanAttributeSpec("seamless")
    lazy val selected = BooleanAttributeSpec("selected")
    lazy val shape = StringAttributeSpec("shape")
    lazy val size = IntegerAttributeSpec("size")
    lazy val sizes = SetOfUniqueSpaceSeparatedStringAttributeSpec("sizes")
    lazy val span = IntegerAttributeSpec("span")
    lazy val spellcheck = TrueOrFalseAttributeSpec("spellcheck")
    lazy val src = StringAttributeSpec("src")
    lazy val srcdoc = StringAttributeSpec("srcdoc")
    lazy val srclang = StringAttributeSpec("srclang")
    lazy val srcset = CommaSeparatedStringAttributeSpec("srcset")
    lazy val start = IntegerAttributeSpec("start")
    lazy val step = BigDecimalOrAnyAttributeSpec("step")
    lazy val style = CssAttributeSpec("style")
    lazy val tabindex = IntegerAttributeSpec("tabindex")
    lazy val target = StringAttributeSpec("target")
    lazy val title = StringAttributeSpec("title")
    lazy val translate = YesOrNoAttributeSpec("translate")
    lazy val `type` = TypeAttributeSpec("type")
    lazy val typemustmatch = BooleanAttributeSpec("typemustmatch")
    lazy val usemap = StringAttributeSpec("usemap")
    lazy val value = ValueAttributeSpec("value")
    lazy val width = IntegerAttributeSpec("width")
    lazy val wmode = WModeAttributeSpec("wmode")
    lazy val wrap = StringAttributeSpec("wrap")

    def apply(name: String) = DynamicAttributeSpec(name)
  }

  val < = new Elements()

  val ^ = new Attributes()

}

object StaticTags extends StaticTags
